export const GET_FEATURED_STREAMS = "GET_FEATURED_STREAMS";
export const SET_GLOBAL_STREAM = "SET_GLOBAL_STREAM";
export const GET_TOP_GAMES = "GET_GAMES";
export const GET_STREAMS_BY_CATEGORY = "GET_STREAMS_FOR_CATEGORY";
export const SET_LOADING = "SET_LOADING";
